<a href="https://colab.research.google.com/github/syedanida/Tensor-Operations/blob/main/pytorch_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Creating Tensors ###

In [68]:
import torch

# Creating a tensor with specific values
tensor_1 = torch.tensor([[1, 2], [3, 4]])
print("tensor_1:\n", tensor_1)

# Creating a tensor of zeros
tensor_2 = torch.zeros(2, 2)
print("\ntensor_2 (zeros):\n", tensor_2)

# Creating a tensor of ones
tensor_3 = torch.ones(2, 2)
print("\ntensor_3 (ones):\n", tensor_3)

tensor_1:
 tensor([[1, 2],
        [3, 4]])

tensor_2 (zeros):
 tensor([[0., 0.],
        [0., 0.]])

tensor_3 (ones):
 tensor([[1., 1.],
        [1., 1.]])


###Checking Tensor Properties###

In [69]:
# Checking shape, dtype, and device
print("\ntensor_1 shape:", tensor_1.shape)
print("tensor_1 dtype:", tensor_1.dtype)
print("tensor_1 device:", tensor_1.device)


tensor_1 shape: torch.Size([2, 2])
tensor_1 dtype: torch.int64
tensor_1 device: cpu


###Moving Tensors between CPU and GPU###

In [70]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor_1 = tensor_1.to(device)
print("\ntensor_1 after moving to device:", tensor_1.device)


tensor_1 after moving to device: cpu


### Element-wise Operations ###

In [71]:
# Element-wise addition
result_add = tensor_1 + tensor_2
print("\nElement-wise addition result:\n", result_add)

# Element-wise subtraction
result_sub = tensor_1 - tensor_2
print("\nElement-wise subtraction result:\n", result_sub)

# Element-wise multiplication
result_mul = tensor_1 * tensor_2
print("\nElement-wise multiplication result:\n", result_mul)

# Element-wise division
result_div = tensor_1 / tensor_2
print("\nElement-wise division result:\n", result_div)


Element-wise addition result:
 tensor([[1., 2.],
        [3., 4.]])

Element-wise subtraction result:
 tensor([[1., 2.],
        [3., 4.]])

Element-wise multiplication result:
 tensor([[0., 0.],
        [0., 0.]])

Element-wise division result:
 tensor([[inf, inf],
        [inf, inf]])


###Matrix Multiplication###

In [72]:
# Assuming tensor_1 is the one with the incorrect dtype
tensor_1 = tensor_1.type(tensor_2.dtype)

# matrix multiplication
result_matmul = tensor_1 @ tensor_2
print("\nMatrix multiplication (@) result:\n", result_matmul)

result_mm = torch.matmul(tensor_1, tensor_2)
print("\nMatrix multiplication (torch.matmul) result:\n", result_mm)


Matrix multiplication (@) result:
 tensor([[0., 0.],
        [0., 0.]])

Matrix multiplication (torch.matmul) result:
 tensor([[0., 0.],
        [0., 0.]])


###Reductions###

In [73]:
# Sum of all elements
sum_result = tensor_1.sum()
print("\nSum of all elements in tensor_1:", sum_result)

# Mean of all elements
mean_result = tensor_1.mean()
print("Mean of all elements in tensor_1:", mean_result)

# Standard deviation
std_result = tensor_1.std()
print("Standard deviation of tensor_1:", std_result)

# Variance
var_result = tensor_1.var()
print("Variance of tensor_1:", var_result)


Sum of all elements in tensor_1: tensor(10.)
Mean of all elements in tensor_1: tensor(2.5000)
Standard deviation of tensor_1: tensor(1.2910)
Variance of tensor_1: tensor(1.6667)


###Slicing###

In [74]:
slice_result = tensor_1[:, 1:]
print("\nSliced tensor (second column to end):\n", slice_result)


Sliced tensor (second column to end):
 tensor([[2.],
        [4.]])


###Reshaping###

In [75]:
# Reshaping tensor
reshaped_tensor = tensor_1.view(1, 4)
print("\nReshaped tensor:\n", reshaped_tensor)


Reshaped tensor:
 tensor([[1., 2., 3., 4.]])


###Expanding and Squeezing Dimensions###

In [76]:
# Expanding a tensor's dimensions
expanded_tensor = tensor_1.unsqueeze(0)
print("\nExpanded tensor:\n", expanded_tensor)

# Removing a dimension of size 1
squeezed_tensor = expanded_tensor.squeeze()
print("\nSqueezed tensor:\n", squeezed_tensor)


Expanded tensor:
 tensor([[[1., 2.],
         [3., 4.]]])

Squeezed tensor:
 tensor([[1., 2.],
        [3., 4.]])


###Broadcasting in PyTorch###

In [77]:
# Broadcasting example
tensor_4 = torch.tensor([1, 2])
result_broadcast = tensor_1 + tensor_4
print("\nBroadcasting result:\n", result_broadcast)


Broadcasting result:
 tensor([[2., 4.],
        [4., 6.]])


###Stacking and Concatenation###

In [78]:
# Stacking tensors along a new dimension
stacked_tensor = torch.stack([tensor_1, tensor_2])
print("\nStacked tensors:\n", stacked_tensor)

# Concatenating tensors along an existing dimension
concatenated_tensor = torch.cat([tensor_1, tensor_2], dim=0)
print("\nConcatenated tensors along dim 0:\n", concatenated_tensor)


Stacked tensors:
 tensor([[[1., 2.],
         [3., 4.]],

        [[0., 0.],
         [0., 0.]]])

Concatenated tensors along dim 0:
 tensor([[1., 2.],
        [3., 4.],
        [0., 0.],
        [0., 0.]])


###Tile and Repeat###

In [79]:
# Repeating elements of the tensor
repeated_tensor = tensor_1.repeat(2, 2)
print("\nRepeated tensor:\n", repeated_tensor)

# Expanding elements of the tensor
expanded_tensor = tensor_1.expand(2, 2)
print("\nExpanded tensor:\n", expanded_tensor)


Repeated tensor:
 tensor([[1., 2., 1., 2.],
        [3., 4., 3., 4.],
        [1., 2., 1., 2.],
        [3., 4., 3., 4.]])

Expanded tensor:
 tensor([[1., 2.],
        [3., 4.]])


###Einstein Summation###

In [80]:
# Example matrix multiplication
einsum_result = torch.einsum('ij,jk->ik', tensor_1, tensor_2)
print("\nEinstein Summation (matrix multiplication) result:\n", einsum_result)

# Transpose with einsum
transpose_result = torch.einsum('ij->ji', tensor_1)
print("\nTranspose result with einsum:\n", transpose_result)

# Outer product
outer_shape = (tensor_1.shape[0] * tensor_1.shape[1], tensor_2.shape[0] * tensor_2.shape[1])
outer_product = torch.einsum('i,j->ij', tensor_1.flatten(), tensor_2.flatten()).reshape(outer_shape)
print("\nOuter product result with einsum:\n", outer_product)

# Summing over axes
summed_result = torch.einsum('ij->i', tensor_1)
print("\nSumming over axes result:\n", summed_result)


Einstein Summation (matrix multiplication) result:
 tensor([[0., 0.],
        [0., 0.]])

Transpose result with einsum:
 tensor([[1., 3.],
        [2., 4.]])

Outer product result with einsum:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Summing over axes result:
 tensor([3., 7.])


###Exploring einops in PyTorch###

In [81]:
!pip install --upgrade einops

In [82]:
# Rearranging tensor with einops
rearranged_tensor = einops.rearrange(tensor_1, 'h w -> w h')
print("\nRearranged tensor with einops:\n", rearranged_tensor)

# Expanding dimensions with einops
expanded_tensor_einops = einops.repeat(tensor_1, 'h w -> h w 1')
print("\nExpanded tensor with einops:\n", expanded_tensor_einops)

# Reducing tensor with einops (e.g., summing over a dimension)
reduced_tensor = einops.reduce(tensor_1, 'h w -> h', reduction='sum')
print("\nReduced tensor with einops (sum over dimension h):\n", reduced_tensor)



Rearranged tensor with einops:
 tensor([[1., 3.],
        [2., 4.]])

Expanded tensor with einops:
 tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])

Reduced tensor with einops (sum over dimension h):
 tensor([3., 7.])


###Eigendecomposition###

In [83]:
# Eigendecomposition of a square matrix
eigenvalues, eigenvectors = torch.linalg.eig(tensor_1)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)


Eigenvalues:
 tensor([-0.3723+0.j,  5.3723+0.j])

Eigenvectors:
 tensor([[-0.8246+0.j, -0.4160+0.j],
        [ 0.5658+0.j, -0.9094+0.j]])


###Singular Value Decomposition (SVD)###

In [84]:
# SVD of a matrix
U, S, V = torch.svd(tensor_1)
print("\nSingular Value Decomposition:\nU:\n", U)
print("S:\n", S)
print("V:\n", V)


Singular Value Decomposition:
U:
 tensor([[-0.4046, -0.9145],
        [-0.9145,  0.4046]])
S:
 tensor([5.4650, 0.3660])
V:
 tensor([[-0.5760,  0.8174],
        [-0.8174, -0.5760]])


###Fast Fourier Transform (FFT)###

In [85]:
# Computing the FFT of a tensor
fft_result = torch.fft.fft(tensor_1)
print("\nFFT result:\n", fft_result)


FFT result:
 tensor([[ 3.+0.j, -1.+0.j],
        [ 7.+0.j, -1.+0.j]])
