<a href="https://colab.research.google.com/github/syedanida/Tensor-Operations/blob/main/tensorflow_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import tensorflow as tf
import numpy as np

# Check TensorFlow version
print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.18.0


### 1. Creating Tensors ###

In [10]:
# Constant tensor
tensor_const = tf.constant([[1, 2], [3, 4]])
print("Constant Tensor:", tensor_const)

Constant Tensor: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [11]:
# Variable tensor
tensor_var = tf.Variable([[5.0, 6.0], [7.0, 8.0]])
print("Variable Tensor:", tensor_var)

Variable Tensor: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[5., 6.],
       [7., 8.]], dtype=float32)>


In [12]:
# Tensor from NumPy array
numpy_array = np.array([[9, 10], [11, 12]])
tensor_from_numpy = tf.convert_to_tensor(numpy_array)
print("Tensor from NumPy:", tensor_from_numpy)

Tensor from NumPy: tf.Tensor(
[[ 9 10]
 [11 12]], shape=(2, 2), dtype=int64)


### 2. Basic Tensor Operations ###

In [13]:
# Element-wise addition, subtraction, multiplication, division
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])
print("Addition:", tensor_a + tensor_b)
print("Multiplication:", tensor_a * tensor_b)
print("Matrix Multiplication:", tf.matmul(tensor_a, tensor_b))

Addition: tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Multiplication: tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Matrix Multiplication: tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [14]:
# Transpose
print("Transpose:", tf.transpose(tensor_a))

Transpose: tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [15]:
# Reshape
reshaped_tensor = tf.reshape(tensor_a, (1, 4))
print("Reshaped Tensor:", reshaped_tensor)

Reshaped Tensor: tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)


### 3. Indexing, Slicing, and Reshaping ###

In [16]:
# Slicing
tensor_c = tf.constant([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original Tensor:", tensor_c)
print("First Row:", tensor_c[0, :])
print("First Column:", tensor_c[:, 0])

Original Tensor: tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)
First Row: tf.Tensor([10 20 30], shape=(3,), dtype=int32)
First Column: tf.Tensor([10 40 70], shape=(3,), dtype=int32)


In [17]:
# Expanding and Squeezing Dimensions
expanded_tensor = tf.expand_dims(tensor_c, axis=0)  # Adds a batch dimension
squeezed_tensor = tf.squeeze(expanded_tensor)  # Removes dimensions of size 1
print("Expanded Tensor:", expanded_tensor)
print("Squeezed Tensor:", squeezed_tensor)

Expanded Tensor: tf.Tensor(
[[[10 20 30]
  [40 50 60]
  [70 80 90]]], shape=(1, 3, 3), dtype=int32)
Squeezed Tensor: tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)


### 4. Advanced Tensor Operations ###

In [18]:
# Broadcasting
tensor_d = tf.constant([[1], [2], [3]])  # Shape (3,1)
tensor_e = tf.constant([1, 2, 3])  # Shape (3,)
broadcasted_sum = tensor_d + tensor_e  # Broadcasting happens here
print("Broadcasted Sum:", broadcasted_sum)

Broadcasted Sum: tf.Tensor(
[[2 3 4]
 [3 4 5]
 [4 5 6]], shape=(3, 3), dtype=int32)


In [19]:
# Stacking and Concatenation
tensor_f = tf.constant([1, 2, 3])
tensor_g = tf.constant([4, 5, 6])
stacked_tensor = tf.stack([tensor_f, tensor_g], axis=1)
concatenated_tensor = tf.concat([tensor_f, tensor_g], axis=0)
print("Stacked Tensor:", stacked_tensor)
print("Concatenated Tensor:", concatenated_tensor)

Stacked Tensor: tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
Concatenated Tensor: tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


### 5. Einstein Summation (einsum) ###

In [20]:
# Matrix Multiplication using einsum
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
einsum_result = tf.einsum('ij,jk->ik', a, b)
print("Einsum Matrix Multiplication:", einsum_result)

Einsum Matrix Multiplication: tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [21]:
# Transpose using einsum
transpose_einsum = tf.einsum('ij->ji', a)
print("Einsum Transpose:", transpose_einsum)

Einsum Transpose: tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [22]:
# Outer Product using einsum
vector_x = tf.constant([1, 2, 3])
vector_y = tf.constant([4, 5, 6])
outer_product = tf.einsum('i,j->ij', vector_x, vector_y)
print("Einsum Outer Product:", outer_product)

Einsum Outer Product: tf.Tensor(
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]], shape=(3, 3), dtype=int32)


### 6. Creative Tensor Operations ###

In [23]:
# Eigendecomposition
eigenvalues, eigenvectors = tf.linalg.eig(tf.cast(a, tf.complex64))
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: tf.Tensor([-0.37228122+0.j  5.372281  +0.j], shape=(2,), dtype=complex64)
Eigenvectors: tf.Tensor(
[[-0.8245648 +0.j -0.41597357+0.j]
 [ 0.56576747+0.j -0.90937674+0.j]], shape=(2, 2), dtype=complex64)


In [24]:
# Singular Value Decomposition (SVD)
svd_result = tf.linalg.svd(tf.cast(a, tf.float32))
print("SVD Result:", svd_result)

SVD Result: (<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.4649854 , 0.36596614], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.4045535, -0.9145143],
       [ 0.9145143,  0.4045535]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.5760484,  0.8174156],
       [ 0.8174156, -0.5760484]], dtype=float32)>)


In [25]:
# FFT Transformation
fft_tensor = tf.signal.fft(tf.cast([1.0, 2.0, 3.0, 4.0], tf.complex64))
print("FFT Result:", fft_tensor)

FFT Result: tf.Tensor([10.+0.j -2.+2.j -2.+0.j -2.-2.j], shape=(4,), dtype=complex64)
